In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("../data/processed/all_sales.csv")

df.head()

,date,sku,item_name,unit_upc,case_upc,quantity,unit_price,total_sales
0,2024-01-02,13353,Natural Light 2x 15 Pack (12 oz Cans),18200000317,18200200779,5,20.35,101.75
1,2024-01-02,15032,Michelob Ultra Infusions Lime and Prickly Pear...,18200007941,18200200199,1,31.50,31.50
2,2024-01-02,15800,Budweiser 30 Pack (12 oz Cans),18200000164,18200110306,1,29.00,29.00
3,2024-01-02,17100,Natural Light 30 Pack (12 oz Cans),18200000317,18200150302,1,21.15,21.15
4,2024-01-02,18048,Michelob Ultra 15 Pack (25 oz Cans),18200250101,18200960116,1,39.75,39.75

In [5]:
df.shape

(2620, 8)

In [7]:
df.sample(10)

,date,sku,item_name,unit_upc,case_upc,quantity,unit_price,total_sales
1734,2025-06-17,34000,Bud Light 2x 12 Pack (12 oz Bottles),18200001697,18200533600,5,26.70,133.50
2089,2025-09-30,30504,Michelob Ultra 18 Pack (12 oz Bottles),18200003325,18200966248,4,21.65,86.60
1658,2025-05-27,31100,Bud Light 20 Pack (12 oz Bottles),18200001697,18200530258,4,17.45,69.80
1405,2025-03-18,24600,Michelob Ultra 4x 6 Pack (16 oz Cans),18200001581,18200287381,2,34.75,69.50
1393,2025-03-18,13922,Bud Light Platinum 4x 6 Pack (12 oz Bottles),18200009075,18200961182,1,31.10,31.10
1637,2025-05-27,11500,Bud Light 18 Pack (12 oz Cans),18200001062,18200532184,5,16.65,83.25
965,2024-10-22,24600,Michelob Ultra 4x 6 Pack (16 oz Cans),18200001581,18200287381,2,34.75,69.50
1243,2025-01-21,24800,Natural Light 4x 6 Pack (16 oz Cans),18200000430,18200150432,1,22.01,22.01
37,2024-01-16,17100,Natural Light 30 Pack (12 oz Cans),18200000317,18200150302,2,21.15,42.30
2226,2025-11-11,15977,Budweiser Zero (Non-Alc) 2x 12 Pack (12 oz Cans),18200258619,18200283659,3,26.70,80.10

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         2620 non-null   str
 1   sku          2620 non-null   int64
 2   item_name    2620 non-null   str
 3   unit_upc     2620 non-null   int64
 4   case_upc     2620 non-null   int64
 5   quantity     2620 non-null   int64
 6   unit_price   2620 non-null   float64
 7   total_sales  2620 non-null   float64
dtypes: float64(2), int64(4), str(2)
memory usage: 163.9 KB

In [11]:
df.describe()

,sku,unit_upc,case_upc,quantity,unit_price,total_sales
count,2620.000000,2.620000e+03,2.620000e+03,2620.000000,2620.000000,2620.000000
mean,22258.440458,3.681090e+10,8.022759e+10,2.305725,28.487874,61.509882
std,8912.872077,1.157086e+11,9.396295e+11,2.129101,6.678846,52.860980
min,11300.000000,1.820000e+10,1.820011e+10,-7.000000,16.650000,-165.900000
25%,16000.000000,1.820000e+10,1.820037e+10,1.000000,22.010000,31.100000
50%,18900.000000,1.820000e+10,1.820054e+10,2.000000,30.000000,42.300000
75%,25106.000000,1.820001e+10,1.820096e+10,3.000000,32.700000,70.500000
max,48720.000000,8.511330e+11,2.085005e+13,15.000000,43.150000,421.500000

In [13]:
df.columns

Index(['date', 'sku', 'item_name', 'unit_upc', 'case_upc', 'quantity',
       'unit_price', 'total_sales'],
      dtype='str')

In [15]:
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date")

In [17]:
print("Rows:", len(df))
print("Unique SKUs:", df["sku"].nunique())
print("Date range:", df["date"].min(), "→", df["date"].max())

Rows: 2620
Unique SKUs: 98
Date range: 2024-01-02 00:00:00 → 2026-03-17 00:00:00

In [19]:
df["quantity"].describe()

count    2620.000000
mean        2.305725
std         2.129101
min        -7.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        15.000000
Name: quantity, dtype: float64

In [20]:
df.isnull().sum()

date           0
sku            0
item_name      0
unit_upc       0
case_upc       0
quantity       0
unit_price     0
total_sales    0
dtype: int64